// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package admin

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	lock "github.com/use-lock/client-go"
	transport "github.com/use-lock/client-go/internal/transport"
)

// Defines values for RealmDomainStatus.
const (
	RealmDomainStatusMisrouted   RealmDomainStatus = "misrouted"
	RealmDomainStatusPending     RealmDomainStatus = "pending"
	RealmDomainStatusUnreachable RealmDomainStatus = "unreachable"
	RealmDomainStatusVerified    RealmDomainStatus = "verified"
)

// Valid indicates whether the value is a known member of the RealmDomainStatus enum.
func (e RealmDomainStatus) Valid() bool {
	switch e {
	case RealmDomainStatusMisrouted:
		return true
	case RealmDomainStatusPending:
		return true
	case RealmDomainStatusUnreachable:
		return true
	case RealmDomainStatusVerified:
		return true
	default:
		return false
	}
}

// Defines values for ListRealmsParamsSort.
const (
	CreatedAt      ListRealmsParamsSort = "created_at"
	MinusCreatedAt ListRealmsParamsSort = "-created_at"
	MinusName      ListRealmsParamsSort = "-name"
	MinusSlug      ListRealmsParamsSort = "-slug"
	Name           ListRealmsParamsSort = "name"
	Slug           ListRealmsParamsSort = "slug"
)

// Valid indicates whether the value is a known member of the ListRealmsParamsSort enum.
func (e ListRealmsParamsSort) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case MinusCreatedAt:
		return true
	case MinusName:
		return true
	case MinusSlug:
		return true
	case Name:
		return true
	case Slug:
		return true
	default:
		return false
	}
}

// Defines values for ListRealmsParamsFilterDomainStatus.
const (
	ListRealmsParamsFilterDomainStatusMisrouted   ListRealmsParamsFilterDomainStatus = "misrouted"
	ListRealmsParamsFilterDomainStatusPending     ListRealmsParamsFilterDomainStatus = "pending"
	ListRealmsParamsFilterDomainStatusUnreachable ListRealmsParamsFilterDomainStatus = "unreachable"
	ListRealmsParamsFilterDomainStatusVerified    ListRealmsParamsFilterDomainStatus = "verified"
)

// Valid indicates whether the value is a known member of the ListRealmsParamsFilterDomainStatus enum.
func (e ListRealmsParamsFilterDomainStatus) Valid() bool {
	switch e {
	case ListRealmsParamsFilterDomainStatusMisrouted:
		return true
	case ListRealmsParamsFilterDomainStatusPending:
		return true
	case ListRealmsParamsFilterDomainStatusUnreachable:
		return true
	case ListRealmsParamsFilterDomainStatusVerified:
		return true
	default:
		return false
	}
}

// Defines values for ListRealms401JSONResponseBodyError.
const (
	ListRealms401JSONResponseBodyErrorInvalidToken ListRealms401JSONResponseBodyError = "invalid_token"
)

// Valid indicates whether the value is a known member of the ListRealms401JSONResponseBodyError enum.
func (e ListRealms401JSONResponseBodyError) Valid() bool {
	switch e {
	case ListRealms401JSONResponseBodyErrorInvalidToken:
		return true
	default:
		return false
	}
}

// Defines values for ListRealms403JSONResponseBodyError.
const (
	ListRealms403JSONResponseBodyErrorInsufficientScope ListRealms403JSONResponseBodyError = "insufficient_scope"
)

// Valid indicates whether the value is a known member of the ListRealms403JSONResponseBodyError enum.
func (e ListRealms403JSONResponseBodyError) Valid() bool {
	switch e {
	case ListRealms403JSONResponseBodyErrorInsufficientScope:
		return true
	default:
		return false
	}
}

// Defines values for CreateRealm401JSONResponseBodyError.
const (
	CreateRealm401JSONResponseBodyErrorInvalidToken CreateRealm401JSONResponseBodyError = "invalid_token"
)

// Valid indicates whether the value is a known member of the CreateRealm401JSONResponseBodyError enum.
func (e CreateRealm401JSONResponseBodyError) Valid() bool {
	switch e {
	case CreateRealm401JSONResponseBodyErrorInvalidToken:
		return true
	default:
		return false
	}
}

// Defines values for CreateRealm403JSONResponseBodyError.
const (
	CreateRealm403JSONResponseBodyErrorInsufficientScope CreateRealm403JSONResponseBodyError = "insufficient_scope"
)

// Valid indicates whether the value is a known member of the CreateRealm403JSONResponseBodyError enum.
func (e CreateRealm403JSONResponseBodyError) Valid() bool {
	switch e {
	case CreateRealm403JSONResponseBodyErrorInsufficientScope:
		return true
	default:
		return false
	}
}

// Defines values for DeleteRealm401JSONResponseBodyError.
const (
	DeleteRealm401JSONResponseBodyErrorInvalidToken DeleteRealm401JSONResponseBodyError = "invalid_token"
)

// Valid indicates whether the value is a known member of the DeleteRealm401JSONResponseBodyError enum.
func (e DeleteRealm401JSONResponseBodyError) Valid() bool {
	switch e {
	case DeleteRealm401JSONResponseBodyErrorInvalidToken:
		return true
	default:
		return false
	}
}

// Defines values for DeleteRealm403JSONResponseBodyError.
const (
	DeleteRealm403JSONResponseBodyErrorInsufficientScope DeleteRealm403JSONResponseBodyError = "insufficient_scope"
)

// Valid indicates whether the value is a known member of the DeleteRealm403JSONResponseBodyError enum.
func (e DeleteRealm403JSONResponseBodyError) Valid() bool {
	switch e {
	case DeleteRealm403JSONResponseBodyErrorInsufficientScope:
		return true
	default:
		return false
	}
}

// Defines values for GetRealm401JSONResponseBodyError.
const (
	GetRealm401JSONResponseBodyErrorInvalidToken GetRealm401JSONResponseBodyError = "invalid_token"
)

// Valid indicates whether the value is a known member of the GetRealm401JSONResponseBodyError enum.
func (e GetRealm401JSONResponseBodyError) Valid() bool {
	switch e {
	case GetRealm401JSONResponseBodyErrorInvalidToken:
		return true
	default:
		return false
	}
}

// Defines values for GetRealm403JSONResponseBodyError.
const (
	GetRealm403JSONResponseBodyErrorInsufficientScope GetRealm403JSONResponseBodyError = "insufficient_scope"
)

// Valid indicates whether the value is a known member of the GetRealm403JSONResponseBodyError enum.
func (e GetRealm403JSONResponseBodyError) Valid() bool {
	switch e {
	case GetRealm403JSONResponseBodyErrorInsufficientScope:
		return true
	default:
		return false
	}
}

// Defines values for PatchRealm401JSONResponseBodyError.
const (
	PatchRealm401JSONResponseBodyErrorInvalidToken PatchRealm401JSONResponseBodyError = "invalid_token"
)

// Valid indicates whether the value is a known member of the PatchRealm401JSONResponseBodyError enum.
func (e PatchRealm401JSONResponseBodyError) Valid() bool {
	switch e {
	case PatchRealm401JSONResponseBodyErrorInvalidToken:
		return true
	default:
		return false
	}
}

// Defines values for PatchRealm403JSONResponseBodyError.
const (
	PatchRealm403JSONResponseBodyErrorInsufficientScope PatchRealm403JSONResponseBodyError = "insufficient_scope"
)

// Valid indicates whether the value is a known member of the PatchRealm403JSONResponseBodyError enum.
func (e PatchRealm403JSONResponseBodyError) Valid() bool {
	switch e {
	case PatchRealm403JSONResponseBodyErrorInsufficientScope:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRealm401JSONResponseBodyError.
const (
	UpdateRealm401JSONResponseBodyErrorInvalidToken UpdateRealm401JSONResponseBodyError = "invalid_token"
)

// Valid indicates whether the value is a known member of the UpdateRealm401JSONResponseBodyError enum.
func (e UpdateRealm401JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateRealm401JSONResponseBodyErrorInvalidToken:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRealm403JSONResponseBodyError.
const (
	UpdateRealm403JSONResponseBodyErrorInsufficientScope UpdateRealm403JSONResponseBodyError = "insufficient_scope"
)

// Valid indicates whether the value is a known member of the UpdateRealm403JSONResponseBodyError enum.
func (e UpdateRealm403JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateRealm403JSONResponseBodyErrorInsufficientScope:
		return true
	default:
		return false
	}
}

// CreateRealmData defines model for CreateRealmData.
type CreateRealmData struct {
	// Domain The domain the realm is served from. Lock checks that it reaches this instance, but keeps the realm either way.
	Domain string `json:"domain"`

	// Name Human readable name shown to the realm’s users.
	Name string `json:"name"`

	// Settings The realm’s policy. Settings left out follow the instance defaults.
	Settings *RealmSettingsPatch `json:"settings,omitempty"`

	// Slug Stable identifier, lowercase and dash separated. It cannot be changed later.
	Slug string `json:"slug"`
}

// RealmCollection defines model for RealmCollection.
type RealmCollection struct {
	Data  []RealmData `json:"data"`
	Links []struct {
		Active bool                      `json:"active"`
		Label  string                    `json:"label"`
		URL    nullable.Nullable[string] `json:"url"`
	} `json:"links"`
	Meta struct {
		CurrentPage  int                       `json:"current_page"`
		FirstPageURL nullable.Nullable[string] `json:"first_page_url"`
		From         nullable.Nullable[int]    `json:"from"`
		LastPage     int                       `json:"last_page"`
		LastPageURL  nullable.Nullable[string] `json:"last_page_url"`
		NextPageURL  nullable.Nullable[string] `json:"next_page_url"`
		Path         nullable.Nullable[string] `json:"path"`
		PerPage      int                       `json:"per_page"`
		PrevPageURL  nullable.Nullable[string] `json:"prev_page_url"`
		To           nullable.Nullable[int]    `json:"to"`
		Total        int                       `json:"total"`
	} `json:"meta"`
}

// RealmData defines model for RealmData.
type RealmData struct {
	// CreatedAt When the realm was created.
	CreatedAt nullable.Nullable[string] `json:"created_at,omitempty"`

	// Domain The configured domain; null for the master realm, which follows APP_URL.
	Domain nullable.Nullable[string] `json:"domain,omitempty"`

	// DomainCheckError Why the last domain check failed, when it did.
	DomainCheckError nullable.Nullable[string] `json:"domain_check_error,omitempty"`

	// DomainCheckedAt When the domain was last checked.
	DomainCheckedAt nullable.Nullable[string] `json:"domain_checked_at,omitempty"`

	// DomainStatus Whether the configured domain was seen to reach this instance.
	DomainStatus RealmDomainStatus `json:"domain_status"`

	// Host The host the realm is served from.
	Host string `json:"host"`

	// Issuer The realm’s OIDC issuer, the `iss` of every token it mints.
	Issuer string `json:"issuer"`

	// Master Whether this is the administration realm, which cannot be deleted or re-pointed.
	Master bool `json:"master"`

	// Name Human readable name shown to its users.
	Name string `json:"name"`

	// Settings The realm’s own policy.
	Settings RealmSettings `json:"settings"`

	// Slug Stable identifier of the realm, and its path in this API.
	Slug string `json:"slug"`

	// UpdatedAt When the realm was last changed.
	UpdatedAt nullable.Nullable[string] `json:"updated_at,omitempty"`
}

// RealmDomainStatus What the last domain check found. `Unreachable` means no HTTP answer at all (DNS, connection, TLS); `Misrouted` means something answered, but not this Lock instance.
type RealmDomainStatus string

// RealmResponse defines model for RealmResponse.
type RealmResponse struct {
	Data RealmData `json:"data"`
}

// RealmSettings defines model for RealmSettings.
type RealmSettings struct {
	// AccessTokenLifetime Seconds an access token stays valid.
	AccessTokenLifetime float32 `json:"access_token_lifetime"`

	// AllowedRedirectDomains Hosts a redirect URI may point at; `*` allows any.
	AllowedRedirectDomains []string `json:"allowed_redirect_domains"`

	// AllowedRedirectSchemes URI schemes a redirect URI may use.
	AllowedRedirectSchemes []string `json:"allowed_redirect_schemes"`

	// AutoProvision Create a realm user on their first verified upstream sign-in.
	AutoProvision bool `json:"auto_provision"`

	// ChallengeProviders The second factors on offer: `totp`, `webauthn`.
	ChallengeProviders []string `json:"challenge_providers"`

	// ClientCredentialsLifetime Seconds a token issued to a machine client stays valid.
	ClientCredentialsLifetime float32 `json:"client_credentials_lifetime"`

	// DefaultScopes Scopes every client is granted without asking.
	DefaultScopes []string `json:"default_scopes"`

	// DynamicRegistration Whether a client may register itself through RFC 7591.
	DynamicRegistration bool `json:"dynamic_registration"`

	// EmailVerificationRequired Whether an unverified address blocks sign-in.
	EmailVerificationRequired bool `json:"email_verification_required"`

	// FirstPartyTrusted Whether the first-party client skips the consent screen.
	FirstPartyTrusted bool `json:"first_party_trusted"`

	// IDTokenLifetime Seconds an ID token stays valid.
	IDTokenLifetime float32 `json:"id_token_lifetime"`

	// LinkByVerifiedEmail Link an upstream identity to a local user with the same verified email address.
	LinkByVerifiedEmail bool `json:"link_by_verified_email"`

	// LoginMethods The ways an identity may sign in: `password`, `passkey`, `social`.
	LoginMethods []string `json:"login_methods"`

	// MfaRequirement When a second factor is demanded: `never`, `if_enrolled`, `always`.
	MfaRequirement string `json:"mfa_requirement"`

	// OptionalScopes Scopes a client may request on top; `*` allows any of the catalog.
	OptionalScopes []string `json:"optional_scopes"`

	// PasswordHistory How many previous passwords may not be reused.
	PasswordHistory float32 `json:"password_history"`

	// PasswordMaxAgeDays Days before a password must be changed; `0` never expires.
	PasswordMaxAgeDays float32 `json:"password_max_age_days"`

	// PasswordMinLength Shortest password accepted.
	PasswordMinLength float32 `json:"password_min_length"`

	// PasswordMixedCase Whether a password must mix upper and lower case.
	PasswordMixedCase bool `json:"password_mixed_case"`

	// PasswordNumbers Whether a password must carry a digit.
	PasswordNumbers bool `json:"password_numbers"`

	// PasswordSymbols Whether a password must carry a symbol.
	PasswordSymbols bool `json:"password_symbols"`

	// PasswordUncompromised Whether a password is checked against known breaches.
	PasswordUncompromised bool `json:"password_uncompromised"`

	// RecoveryCodes How many recovery codes an identity is issued.
	RecoveryCodes float32 `json:"recovery_codes"`

	// RefreshTokenLifetime Seconds a refresh token stays valid.
	RefreshTokenLifetime float32 `json:"refresh_token_lifetime"`

	// SessionAbsoluteLifetime Seconds a sign-in session lives at most, however often it is refreshed.
	SessionAbsoluteLifetime float32 `json:"session_absolute_lifetime"`

	// SessionTokenRefreshSkew Seconds before expiry at which a session token is refreshed early.
	SessionTokenRefreshSkew float32 `json:"session_token_refresh_skew"`

	// SessionTokenTTL Seconds a session token stays valid before it is refreshed.
	SessionTokenTTL float32 `json:"session_token_ttl"`

	// TokenExchange Whether the RFC 8693 token exchange grant is served.
	TokenExchange bool `json:"token_exchange"`

	// TotpSecretLength Bytes of a generated TOTP secret.
	TotpSecretLength float32 `json:"totp_secret_length"`

	// TotpWindow Time steps either side of now a TOTP code is accepted in.
	TotpWindow float32 `json:"totp_window"`

	// TrustedClients Client ids that skip the consent screen.
	TrustedClients []string `json:"trusted_clients"`
}

// RealmSettingsPatch defines model for RealmSettingsPatch.
type RealmSettingsPatch struct {
	// AccessTokenLifetime Seconds an access token stays valid.
	AccessTokenLifetime *float32 `json:"access_token_lifetime,omitempty"`

	// AllowedRedirectDomains Hosts a redirect URI may point at; `*` allows any.
	AllowedRedirectDomains *[]string `json:"allowed_redirect_domains,omitempty"`

	// AllowedRedirectSchemes URI schemes a redirect URI may use.
	AllowedRedirectSchemes *[]string `json:"allowed_redirect_schemes,omitempty"`

	// AutoProvision Create a realm user on their first verified upstream sign-in.
	AutoProvision *bool `json:"auto_provision,omitempty"`

	// ChallengeProviders The second factors on offer: `totp`, `webauthn`.
	ChallengeProviders *[]string `json:"challenge_providers,omitempty"`

	// ClientCredentialsLifetime Seconds a token issued to a machine client stays valid.
	ClientCredentialsLifetime *float32 `json:"client_credentials_lifetime,omitempty"`

	// DefaultScopes Scopes every client is granted without asking.
	DefaultScopes *[]string `json:"default_scopes,omitempty"`

	// DynamicRegistration Whether a client may register itself through RFC 7591.
	DynamicRegistration *bool `json:"dynamic_registration,omitempty"`

	// EmailVerificationRequired Whether an unverified address blocks sign-in.
	EmailVerificationRequired *bool `json:"email_verification_required,omitempty"`

	// FirstPartyTrusted Whether the first-party client skips the consent screen.
	FirstPartyTrusted *bool `json:"first_party_trusted,omitempty"`

	// IDTokenLifetime Seconds an ID token stays valid.
	IDTokenLifetime *float32 `json:"id_token_lifetime,omitempty"`

	// LinkByVerifiedEmail Link an upstream identity to a local user with the same verified email address.
	LinkByVerifiedEmail *bool `json:"link_by_verified_email,omitempty"`

	// LoginMethods The ways an identity may sign in: `password`, `passkey`, `social`.
	LoginMethods *[]string `json:"login_methods,omitempty"`

	// MfaRequirement When a second factor is demanded: `never`, `if_enrolled`, `always`.
	MfaRequirement *string `json:"mfa_requirement,omitempty"`

	// OptionalScopes Scopes a client may request on top; `*` allows any of the catalog.
	OptionalScopes *[]string `json:"optional_scopes,omitempty"`

	// PasswordHistory How many previous passwords may not be reused.
	PasswordHistory *float32 `json:"password_history,omitempty"`

	// PasswordMaxAgeDays Days before a password must be changed; `0` never expires.
	PasswordMaxAgeDays *float32 `json:"password_max_age_days,omitempty"`

	// PasswordMinLength Shortest password accepted.
	PasswordMinLength *float32 `json:"password_min_length,omitempty"`

	// PasswordMixedCase Whether a password must mix upper and lower case.
	PasswordMixedCase *bool `json:"password_mixed_case,omitempty"`

	// PasswordNumbers Whether a password must carry a digit.
	PasswordNumbers *bool `json:"password_numbers,omitempty"`

	// PasswordSymbols Whether a password must carry a symbol.
	PasswordSymbols *bool `json:"password_symbols,omitempty"`

	// PasswordUncompromised Whether a password is checked against known breaches.
	PasswordUncompromised *bool `json:"password_uncompromised,omitempty"`

	// RecoveryCodes How many recovery codes an identity is issued.
	RecoveryCodes *float32 `json:"recovery_codes,omitempty"`

	// RefreshTokenLifetime Seconds a refresh token stays valid.
	RefreshTokenLifetime *float32 `json:"refresh_token_lifetime,omitempty"`

	// SessionAbsoluteLifetime Seconds a sign-in session lives at most, however often it is refreshed.
	SessionAbsoluteLifetime *float32 `json:"session_absolute_lifetime,omitempty"`

	// SessionTokenRefreshSkew Seconds before expiry at which a session token is refreshed early.
	SessionTokenRefreshSkew *float32 `json:"session_token_refresh_skew,omitempty"`

	// SessionTokenTTL Seconds a session token stays valid before it is refreshed.
	SessionTokenTTL *float32 `json:"session_token_ttl,omitempty"`

	// TokenExchange Whether the RFC 8693 token exchange grant is served.
	TokenExchange *bool `json:"token_exchange,omitempty"`

	// TotpSecretLength Bytes of a generated TOTP secret.
	TotpSecretLength *float32 `json:"totp_secret_length,omitempty"`

	// TotpWindow Time steps either side of now a TOTP code is accepted in.
	TotpWindow *float32 `json:"totp_window,omitempty"`

	// TrustedClients Client ids that skip the consent screen.
	TrustedClients *[]string `json:"trusted_clients,omitempty"`
}

// UpdateRealmData defines model for UpdateRealmData.
type UpdateRealmData struct {
	// Domain The domain the realm is served from. Re-pointing it changes the issuer and restarts the domain check.
	Domain *string `json:"domain,omitempty"`

	// Name Human readable name shown to the realm’s users.
	Name *string `json:"name,omitempty"`

	// Settings Any subset of the realm’s policy; settings left out keep their current value.
	Settings *RealmSettingsPatch `json:"settings,omitempty"`
}

// ModelNotFoundException defines model for ModelNotFoundException.
type ModelNotFoundException struct {
	// Message Error overview.
	Message string `json:"message"`
}

// ValidationException defines model for ValidationException.
type ValidationException struct {
	// Errors A detailed description of each field that failed validation.
	Errors map[string][]string `json:"errors"`

	// Message Errors overview.
	Message string `json:"message"`
}

// ListRealmsParams defines parameters for ListRealms.
type ListRealmsParams struct {
	// Sort Available sorts are `name`, `slug`, `created_at`. You can sort by multiple options by separating them with a comma. To sort in descending order, use `-` sign in front of the sort, for example: `-name`.
	Sort *[]ListRealmsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// FilterName Filter by `name`. Matches values containing the given text, case-insensitively. Separate multiple values with a comma; records matching any value qualify.
	FilterName *[]string `form:"filter[name],omitempty" json:"filter[name],omitempty"`

	// FilterSlug Filter by `slug`. Matches the exact value. Separate multiple values with a comma; records matching any value qualify.
	FilterSlug *[]string `form:"filter[slug],omitempty" json:"filter[slug],omitempty"`

	// FilterDomain Filter by `domain`. Matches the exact value. Separate multiple values with a comma; records matching any value qualify.
	FilterDomain *[]string `form:"filter[domain],omitempty" json:"filter[domain],omitempty"`

	// FilterDomainStatus Filter by `domain_status`. Matches the exact value. Separate multiple values with a comma; records matching any value qualify.
	FilterDomainStatus *[]ListRealmsParamsFilterDomainStatus `form:"filter[domain_status],omitempty" json:"filter[domain_status],omitempty"`

	// Page The page number to retrieve.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage The number of items to retrieve per page.
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ListRealmsParamsSort defines parameters for ListRealms.
type ListRealmsParamsSort string

// ListRealmsParamsFilterDomainStatus defines parameters for ListRealms.
type ListRealmsParamsFilterDomainStatus string

// ListRealms401JSONResponseBodyError defines parameters for ListRealms.
type ListRealms401JSONResponseBodyError string

// ListRealms403JSONResponseBodyError defines parameters for ListRealms.
type ListRealms403JSONResponseBodyError string

// CreateRealm401JSONResponseBodyError defines parameters for CreateRealm.
type CreateRealm401JSONResponseBodyError string

// CreateRealm403JSONResponseBodyError defines parameters for CreateRealm.
type CreateRealm403JSONResponseBodyError string

// DeleteRealm401JSONResponseBodyError defines parameters for DeleteRealm.
type DeleteRealm401JSONResponseBodyError string

// DeleteRealm403JSONResponseBodyError defines parameters for DeleteRealm.
type DeleteRealm403JSONResponseBodyError string

// GetRealm401JSONResponseBodyError defines parameters for GetRealm.
type GetRealm401JSONResponseBodyError string

// GetRealm403JSONResponseBodyError defines parameters for GetRealm.
type GetRealm403JSONResponseBodyError string

// PatchRealm401JSONResponseBodyError defines parameters for PatchRealm.
type PatchRealm401JSONResponseBodyError string

// PatchRealm403JSONResponseBodyError defines parameters for PatchRealm.
type PatchRealm403JSONResponseBodyError string

// UpdateRealm401JSONResponseBodyError defines parameters for UpdateRealm.
type UpdateRealm401JSONResponseBodyError string

// UpdateRealm403JSONResponseBodyError defines parameters for UpdateRealm.
type UpdateRealm403JSONResponseBodyError string

// CreateRealmJSONRequestBody defines body for CreateRealm for application/json ContentType.
type CreateRealmJSONRequestBody = CreateRealmData

// PatchRealmJSONRequestBody defines body for PatchRealm for application/json ContentType.
type PatchRealmJSONRequestBody = UpdateRealmData

// UpdateRealmJSONRequestBody defines body for UpdateRealm for application/json ContentType.
type UpdateRealmJSONRequestBody = UpdateRealmData

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	parsed, err := url.Parse(server)
	if err != nil || parsed.Host == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return nil, fmt.Errorf("lock: invalid API base URL")
	}
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	if client.Client == nil {
		client.Client = &http.Client{CheckRedirect: func(_ *http.Request, _ []*http.Request) error { return http.ErrUseLastResponse }}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListRealms List realms
	//
	// Every realm this instance serves, the administration realm included.
	//
	// Corresponds with GET /v1/realms (the `ListRealms` operationId).
	ListRealms(ctx context.Context, params *ListRealmsParams, reqEditors ...RequestEditorFn) (*RealmCollection, error)

	// CreateRealmWithBody Create a realm
	//
	// The realm gets its own signing keypair, and its domain is checked right
	// away. A domain that does not reach this instance yet is reported through
	// `domain_status` rather than refused — DNS and the proxy usually follow.
	// Settings left out of `settings` follow the instance defaults.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/realms (the `CreateRealm` operationId).
	CreateRealmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealmResponse, error)

	// CreateRealm Create a realm
	//
	// The realm gets its own signing keypair, and its domain is checked right
	// away. A domain that does not reach this instance yet is reported through
	// `domain_status` rather than refused — DNS and the proxy usually follow.
	// Settings left out of `settings` follow the instance defaults.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/realms (the `CreateRealm` operationId).
	CreateRealm(ctx context.Context, body CreateRealmJSONRequestBody, reqEditors ...RequestEditorFn) (*RealmResponse, error)

	// DeleteRealm Delete a realm
	//
	// Purges the realm's users, roles, clients, tokens and keys, and frees its
	// slug. The administration realm cannot be deleted.
	//
	// Corresponds with DELETE /v1/realms/{realm} (the `DeleteRealm` operationId).
	DeleteRealm(ctx context.Context, realm string, reqEditors ...RequestEditorFn) (*Response, error)

	// GetRealm Show a realm
	//
	// Corresponds with GET /v1/realms/{realm} (the `GetRealm` operationId).
	GetRealm(ctx context.Context, realm string, reqEditors ...RequestEditorFn) (*RealmResponse, error)

	// PatchRealmWithBody Update a realm
	//
	// A realm's slug is immutable. Settings left out of `settings` keep
	// their current value. Re-pointing the domain changes the issuer of every
	// token the realm mints and restarts the domain check.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /v1/realms/{realm} (the `PatchRealm` operationId).
	PatchRealmWithBody(ctx context.Context, realm string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealmResponse, error)

	// PatchRealm Update a realm
	//
	// A realm's slug is immutable. Settings left out of `settings` keep
	// their current value. Re-pointing the domain changes the issuer of every
	// token the realm mints and restarts the domain check.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /v1/realms/{realm} (the `PatchRealm` operationId).
	PatchRealm(ctx context.Context, realm string, body PatchRealmJSONRequestBody, reqEditors ...RequestEditorFn) (*RealmResponse, error)

	// UpdateRealmWithBody Update a realm
	//
	// A realm's slug is immutable. Settings left out of `settings` keep
	// their current value. Re-pointing the domain changes the issuer of every
	// token the realm mints and restarts the domain check.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /v1/realms/{realm} (the `UpdateRealm` operationId).
	UpdateRealmWithBody(ctx context.Context, realm string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealmResponse, error)

	// UpdateRealm Update a realm
	//
	// A realm's slug is immutable. Settings left out of `settings` keep
	// their current value. Re-pointing the domain changes the issuer of every
	// token the realm mints and restarts the domain check.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /v1/realms/{realm} (the `UpdateRealm` operationId).
	UpdateRealm(ctx context.Context, realm string, body UpdateRealmJSONRequestBody, reqEditors ...RequestEditorFn) (*RealmResponse, error)
}

// ListRealms List realms
//
// Every realm this instance serves, the administration realm included.
//
// Corresponds with GET /v1/realms (the `ListRealms` operationId).
func (c *Client) ListRealms(ctx context.Context, params *ListRealmsParams, reqEditors ...RequestEditorFn) (*RealmCollection, error) {
	req, err := NewListRealmsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmCollection](c.Client, req, true, 200)
}

// CreateRealmWithBody Create a realm
//
// The realm gets its own signing keypair, and its domain is checked right
// away. A domain that does not reach this instance yet is reported through
// `domain_status` rather than refused — DNS and the proxy usually follow.
// Settings left out of `settings` follow the instance defaults.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/realms (the `CreateRealm` operationId).
func (c *Client) CreateRealmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewCreateRealmRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 201)
}

// CreateRealm Create a realm
//
// The realm gets its own signing keypair, and its domain is checked right
// away. A domain that does not reach this instance yet is reported through
// `domain_status` rather than refused — DNS and the proxy usually follow.
// Settings left out of `settings` follow the instance defaults.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/realms (the `CreateRealm` operationId).
func (c *Client) CreateRealm(ctx context.Context, body CreateRealmJSONRequestBody, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewCreateRealmRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 201)
}

// DeleteRealm Delete a realm
//
// Purges the realm's users, roles, clients, tokens and keys, and frees its
// slug. The administration realm cannot be deleted.
//
// Corresponds with DELETE /v1/realms/{realm} (the `DeleteRealm` operationId).
func (c *Client) DeleteRealm(ctx context.Context, realm string, reqEditors ...RequestEditorFn) (*Response, error) {
	req, err := NewDeleteRealmRequest(c.Server, realm)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[Response](c.Client, req, false, 204)
}

// GetRealm Show a realm
//
// Corresponds with GET /v1/realms/{realm} (the `GetRealm` operationId).
func (c *Client) GetRealm(ctx context.Context, realm string, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewGetRealmRequest(c.Server, realm)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 200)
}

// PatchRealmWithBody Update a realm
//
// A realm's slug is immutable. Settings left out of `settings` keep
// their current value. Re-pointing the domain changes the issuer of every
// token the realm mints and restarts the domain check.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /v1/realms/{realm} (the `PatchRealm` operationId).
func (c *Client) PatchRealmWithBody(ctx context.Context, realm string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewPatchRealmRequestWithBody(c.Server, realm, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 200)
}

// PatchRealm Update a realm
//
// A realm's slug is immutable. Settings left out of `settings` keep
// their current value. Re-pointing the domain changes the issuer of every
// token the realm mints and restarts the domain check.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /v1/realms/{realm} (the `PatchRealm` operationId).
func (c *Client) PatchRealm(ctx context.Context, realm string, body PatchRealmJSONRequestBody, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewPatchRealmRequest(c.Server, realm, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 200)
}

// UpdateRealmWithBody Update a realm
//
// A realm's slug is immutable. Settings left out of `settings` keep
// their current value. Re-pointing the domain changes the issuer of every
// token the realm mints and restarts the domain check.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /v1/realms/{realm} (the `UpdateRealm` operationId).
func (c *Client) UpdateRealmWithBody(ctx context.Context, realm string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewUpdateRealmRequestWithBody(c.Server, realm, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 200)
}

// UpdateRealm Update a realm
//
// A realm's slug is immutable. Settings left out of `settings` keep
// their current value. Re-pointing the domain changes the issuer of every
// token the realm mints and restarts the domain check.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /v1/realms/{realm} (the `UpdateRealm` operationId).
func (c *Client) UpdateRealm(ctx context.Context, realm string, body UpdateRealmJSONRequestBody, reqEditors ...RequestEditorFn) (*RealmResponse, error) {
	req, err := NewUpdateRealmRequest(c.Server, realm, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return transport.Execute[RealmResponse](c.Client, req, true, 200)
}

// NewListRealmsRequest constructs an http.Request for the ListRealms method
func NewListRealmsRequest(server string, params *ListRealmsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/realms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterName != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "filter[name]", *params.FilterName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterSlug != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "filter[slug]", *params.FilterSlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterDomain != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "filter[domain]", *params.FilterDomain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterDomainStatus != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "filter[domain_status]", *params.FilterDomainStatus, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateRealmRequest calls the generic CreateRealm builder with application/json body
func NewCreateRealmRequest(server string, body CreateRealmJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRealmRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateRealmRequestWithBody constructs an http.Request for the CreateRealm method, with any body, and a specified content type
func NewCreateRealmRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/realms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRealmRequest constructs an http.Request for the DeleteRealm method
func NewDeleteRealmRequest(server string, realm string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "realm", realm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/realms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRealmRequest constructs an http.Request for the GetRealm method
func NewGetRealmRequest(server string, realm string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "realm", realm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/realms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchRealmRequest calls the generic PatchRealm builder with application/json body
func NewPatchRealmRequest(server string, realm string, body PatchRealmJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchRealmRequestWithBody(server, realm, "application/json", bodyReader)
}

// NewPatchRealmRequestWithBody constructs an http.Request for the PatchRealm method, with any body, and a specified content type
func NewPatchRealmRequestWithBody(server string, realm string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "realm", realm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/realms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateRealmRequest calls the generic UpdateRealm builder with application/json body
func NewUpdateRealmRequest(server string, realm string, body UpdateRealmJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateRealmRequestWithBody(server, realm, "application/json", bodyReader)
}

// NewUpdateRealmRequestWithBody constructs an http.Request for the UpdateRealm method, with any body, and a specified content type
func NewUpdateRealmRequestWithBody(server string, realm string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "realm", realm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/realms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

type APIError = lock.APIError
type Response = lock.Response

func WithToken(token string) ClientOption {
	return WithRequestEditorFn(func(_ context.Context, req *http.Request) error {
		req.Header.Set("Authorization", "Bearer "+token)
		return nil
	})
}
